-- TABLE
DROP
    TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(64) NOT NULL,
 `price` INT, 
 `size` INT, 
 `quantity` INT, 
 `status` TINYINT DEFAULT '1', 
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 -- INDEX
 PRIMARY KEY (`id`) -- FOR FOREIGN KEY
) ENGINE = INNODB;